[dependencies]
base = "0.11.0"
stable-rbtree = "1.0.0"
stable-buffer = "1.0.1"
prng = "0.0.3"
stableheapbtreemap = "1.5.0"
sha2 = "0.0.4"
cycles-simple = "0.11.4"
stablebuffer = "https://github.com/skilesare/StableBuffer#v0.2.0@110660769d11ba93c618dc4712525d20503bdc37"

[dev-dependencies]
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"

[package]
name = "nacdb"
version = "0.14.3"
description = "A distributed (multi-canister) database with seamless enumeration"
repository = "https://github.com/vporton/NacDB"
keywords = [ "database", "databases" ]
license = "MIT"